
import { Post, User } from '@/types';

// Mock data for users
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'john_doe',
    displayName: 'John Doe',
    email: 'john@example.com',
    profileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=1',
    bio: 'Photographer and traveler',
    createdAt: new Date('2023-01-15'),
  },
  {
    id: '2',
    username: 'jane_smith',
    displayName: 'Jane Smith',
    email: 'jane@example.com',
    profileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=2',
    bio: 'Food lover and coffee enthusiast',
    createdAt: new Date('2023-02-20'),
  },
  {
    id: '3',
    username: 'mike_johnson',
    displayName: 'Mike Johnson',
    email: 'mike@example.com',
    profileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=3',
    bio: 'Tech enthusiast and gamer',
    createdAt: new Date('2023-03-10'),
  },
  {
    id: '4',
    username: 'emily_parks',
    displayName: 'Emily Parks',
    email: 'emily@example.com',
    profileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=4',
    bio: 'Artist and nature lover',
    createdAt: new Date('2023-04-05'),
  },
  {
    id: '5',
    username: 'alex_wong',
    displayName: 'Alex Wong',
    email: 'alex@example.com',
    profileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=5',
    bio: 'Travel blogger and photography enthusiast',
    createdAt: new Date('2023-05-12'),
  },
];

// Mock data for posts
export const mockPosts: Post[] = [
  {
    id: '1',
    userId: '1',
    username: 'john_doe',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=1',
    imageUrl: 'https://source.unsplash.com/random/800x800/?nature&id=1',
    caption: 'Beautiful day in the mountains! #nature #hiking',
    likes: 42,
    comments: 5,
    createdAt: new Date('2023-04-15T10:30:00'),
  },
  {
    id: '2',
    userId: '2',
    username: 'jane_smith',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=2',
    imageUrl: 'https://source.unsplash.com/random/800x800/?food&id=1',
    caption: 'Homemade pasta with fresh ingredients! #foodie #cooking',
    likes: 78,
    comments: 12,
    createdAt: new Date('2023-04-14T18:45:00'),
  },
  {
    id: '3',
    userId: '3',
    username: 'mike_johnson',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=3',
    imageUrl: 'https://source.unsplash.com/random/800x800/?technology&id=1',
    caption: 'New gadget day! Can\'t wait to test this out. #tech #gadgets',
    likes: 36,
    comments: 8,
    createdAt: new Date('2023-04-13T14:20:00'),
  },
  {
    id: '4',
    userId: '1',
    username: 'john_doe',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=1',
    imageUrl: 'https://source.unsplash.com/random/800x800/?travel&id=1',
    caption: 'Sunset views from my latest adventure. #travel #sunset',
    likes: 120,
    comments: 18,
    createdAt: new Date('2023-04-12T20:15:00'),
  },
  {
    id: '5',
    userId: '2',
    username: 'jane_smith',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=2',
    imageUrl: 'https://source.unsplash.com/random/800x800/?coffee&id=1',
    caption: 'Morning coffee ritual. Best way to start the day! #coffee #morning',
    likes: 65,
    comments: 7,
    createdAt: new Date('2023-04-11T08:00:00'),
  },
  {
    id: '6',
    userId: '4',
    username: 'emily_parks',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=4',
    imageUrl: 'https://source.unsplash.com/random/800x800/?art&id=1',
    caption: 'Just finished this painting today. What do you think? #art #creativity',
    likes: 89,
    comments: 15,
    createdAt: new Date('2023-04-10T16:20:00'),
  },
  {
    id: '7',
    userId: '5',
    username: 'alex_wong',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=5',
    imageUrl: 'https://source.unsplash.com/random/800x800/?architecture&id=1',
    caption: 'The architecture in this city is simply breathtaking! #travel #architecture',
    likes: 112,
    comments: 9,
    createdAt: new Date('2023-04-09T12:45:00'),
  },
  {
    id: '8',
    userId: '3',
    username: 'mike_johnson',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=3',
    imageUrl: 'https://source.unsplash.com/random/800x800/?gaming&id=1',
    caption: 'Game night with friends! #gaming #friends',
    likes: 42,
    comments: 6,
    createdAt: new Date('2023-04-08T19:30:00'),
  },
  {
    id: '9',
    userId: '4',
    username: 'emily_parks',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=4',
    imageUrl: 'https://source.unsplash.com/random/800x800/?nature&id=2',
    caption: 'Found this hidden gem during my hike today. #nature #outdoors',
    likes: 76,
    comments: 11,
    createdAt: new Date('2023-04-07T14:15:00'),
  },
  {
    id: '10',
    userId: '5',
    username: 'alex_wong',
    userProfileImage: 'https://source.unsplash.com/random/100x100/?portrait&user=5',
    imageUrl: 'https://source.unsplash.com/random/800x800/?beach&id=1',
    caption: 'Paradise found! The perfect beach day. #travel #beach #paradise',
    likes: 135,
    comments: 21,
    createdAt: new Date('2023-04-06T11:00:00'),
  }
];
